export { default as Home } from './Home'
export { default as News } from './News'
export { default as AddNews } from './AddNews'
export { default as UserAdmin } from './UserAdmin'
export { default as ListCategories } from './ListCategories'
export { default as AddCategory } from './AddCategory'
